apiVersion: apps/v1
kind: Deployment
metadata:
  name: comments2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: comments2
  template:
    metadata:
      labels:
        app: comments2
    spec:
      containers:
        - name: comments2
          image: instagram2/comments2:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
              name: server
              protocol: TCP
          #livenessProbe:
          #  httpGet:
          #    path: /health/live
          #    port: server
          #  initialDelaySeconds: 20
          #  periodSeconds: 5
          #readinessProbe:
          #  httpGet:
          #    path: /health/ready
          #    port: server
          #  initialDelaySeconds: 20
          #  periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: comments2
spec:
  type: LoadBalancer
  ports:
    - port: 8084
      protocol: TCP
      targetPort: server
  selector:
    app: comments2